source "https://rubygems.org"
# https://github.com/just-the-docs/just-the-docs/releases
gem "just-the-docs", "~> 0.4.0.rc4"

# https://github.com/github/pages-gem/releases
gem "github-pages", "~> 227"
