source "https://rubygems.org"

# NOTE: this fixes the relevant jekyll version
# https://github.com/github/pages-gem/releases
gem "github-pages", "~> 231", group: :jekyll_plugins

# https://github.com/just-the-docs/just-the-docs/releases
gem "just-the-docs", "~> 0.8.1"
