# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# This workflow will publish any new release to the npmjs registry

name: Publish Release

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          # NOTE: the explicit registry-url is currently needed for the auth token to work
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false
      # NOTE: the npm update is needed for trusted publisher id-token integration to work
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm publish --access public
