# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# This workflow will publish any new release to the npmjs registry

name: Publish Release

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          # NOTE: the explicit registry-url is currently needed for the auth token to work
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false
      # NOTE: the npm update is needed for trusted publisher id-token integration to work
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm publish --access public
